# Diccionario con los lugares más relevantes por provincia.
diccionario = {
    "Pichincha": {"quito", "cayambe", "machachi", "aloag", "sangolqui", "tabacundo"},
    "Guayas": {"guayaquil", "balao", "balzar", "daule", "durán", "milagro"},
    "Esmeraldas": {"esmeraldas", "atacames", "rioverde", "eloy alfaro", "muisne", "quinindé"},
    "Manabi": {"portoviejo", "bahia de caraquez", "pedernales", "manta", "chone", "el carmen", "jama", "puerto lopez"},
    "Santo Domingo de los Tsachilas": {"santo", "alluriquin", "concordia"},
    "Los Rios": {"babahoyo", "quevedo", "montalvo", "puebloviejo", "vinces"},
    "Santa Elena": {"santa elena", "salinas", "montañita"},
    "Azuay": {"cuenca", "girón", "gualaceo"},
    "El Oro": {"machala", "arenillas", "huaquillas", "sabanilla"},
    "Galápagos": {"baquerizo", "ayora", "villamil", "bellavista"},
    "Carchi": {"tulcan", "mira", "el ángel", "huaca"},
    "Imbabura": {"ibarra", "atuntaqui", "cotacachi", "otavalo", "pimampiro"},
    "Cotopaxi": {"latacunga", "salcedo", "pujilí", "saquisili", "lasso", "la mana", "sigchos"},
    "Tungurahua": {"ambato", "baños", "patate", "pelileo", "píllaro"},
    "Bolivar": {"guaranda", "Guaranda", "echeandia", "salinas"},
    "Chimborazo": {"riobamba", "colta", "guamote", "penipe", "guano"},
    "Canar": {"azogues", "cojitambo", "taday", "Guapan", "Charasol", "Cordero"},
    "Loja": {"loja", "calvas", "catacocha", 'catamayo'},
    "Sucumbios": {"lumbaqui", "loja", "shushufindi"},
    "Orellana": {"orellana", "loreto", "aguarico", "sachas", "coca"},
    "Napo": {"tena", "Achidona", "Baeza", "el chaco"},
    "Pastaza": {"puyo", "clara", "Arajuno", "Mera"},
    "Morona Santiago": {"macas", "gualaquiza", "Palora", 'santiago', 'sucua'},
    "Zamora Chinchipe": {"zamora", "Guayzimi", "Yacuambi", "yantzaza"},
}
